name: Download and Upload File

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download file
        run: |
          curl -L "https://vscode.download.prss.microsoft.com/dbazure/download/stable/10c8e557c8b9f9ed0a87f61f1c9a44bde731c409/code_1.117.0-1776814346_amd64.deb" -o code.deb

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Commit and push
        run: |
          git add code.deb
          git commit -m "auto update file" || echo "No changes to commit"
          git push
